"""Game configuration constants."""

MAX_PLAYERS_PER_GAME = 50
MIN_PLAYERS_TO_START = 2
TOTAL_STATIONS = 10
MAX_ATTEMPTS_PER_WORD = 6
MATCHMAKING_TIMEOUT_SECONDS = 30
GAME_TYPE_HANGMAN = "hangman"
WS_PING_INTERVAL = 30
